default: &default
  adapter : postgresql
  port    : 5432
  host: 127.0.0.1
  username: postgres
  password: postgres
  pool: 10
  timeout: 5000

development:
  <<: *default
  password: root
  database: sample_dev

test:
  <<: *default
  database: sample_test

production:
  <<: *default
  database: sample_prod
